 const fruits = [
   {
     id: 1,
     name: "Apple",
     price: 120,
     image:
       "https://cdn.britannica.com/22/187222-050-07B17FB6/apples-on-a-tree-branch.jpg",
   },
   {
     id: 2,
     name: "Banana",
     price: 60,
     image:
       "https://thevegetablebazaar.in/wp-content/uploads/2022/04/Banana-Kela.png",
   },
   {
     id: 3,
     name: "Orange",
     price: 80,
     image:
       "https://3.imimg.com/data3/GG/NO/MY-12683552/orange-fruits-500x500.jpg",
   },
   {
     id: 4,
     name: "Grapes",
     price: 200,
     image:
       "https://media.istockphoto.com/id/489520104/photo/green-grape-isolated-on-white-background.jpg?s=612x612&w=0&k=20&c=9kg_3pMeBKYnHHjx2JECF61QwzxTikLaQ2w-6A5tOO0=",
   },
   {
     id: 5,
     name: "Pineapple",
     price: 150,
     image:
       "https://www.healthxchange.sg/sites/hexassets/Assets/food-nutrition/pineapple-health-benefits-and-ways-to-enjoy.jpg",
   },
   {
     id: 6,
     name: "Mango",
     price: 100,
     image: "https://via.placeholder.com/150?text=Mango",
   },
   {
     id: 7,
     name: "Watermelon",
     price: 50,
     image: "https://via.placeholder.com/150?text=Watermelon",
   },
   {
     id: 8,
     name: "Peach",
     price: 130,
     image: "https://via.placeholder.com/150?text=Peach",
   },
   {
     id: 9,
     name: "Strawberry",
     price: 180,
     image: "https://via.placeholder.com/150?text=Strawberry",
   },
   {
     id: 10,
     name: "Blueberry",
     price: 250,
     image: "https://via.placeholder.com/150?text=Blueberry",
   },
   {
     id: 11,
     name: "Lemon",
     price: 50,
     image: "https://via.placeholder.com/150?text=Lemon",
   },
   {
     id: 12,
     name: "Pomegranate",
     price: 200,
     image: "https://via.placeholder.com/150?text=Pomegranate",
   },
   {
     id: 13,
     name: "Cherries",
     price: 300,
     image: "https://via.placeholder.com/150?text=Cherries",
   },
   {
     id: 14,
     name: "Avocado",
     price: 180,
     image: "https://via.placeholder.com/150?text=Avocado",
   },
   {
     id: 15,
     name: "Kiwi",
     price: 220,
     image: "https://via.placeholder.com/150?text=Kiwi",
   },
   {
     id: 16,
     name: "Papaya",
     price: 120,
     image: "https://via.placeholder.com/150?text=Papaya",
   },
   {
     id: 17,
     name: "Guava",
     price: 90,
     image: "https://via.placeholder.com/150?text=Guava",
   },
   {
     id: 18,
     name: "Plum",
     price: 160,
     image: "https://via.placeholder.com/150?text=Plum",
   },
   {
     id: 19,
     name: "Lychee",
     price: 250,
     image: "https://via.placeholder.com/150?text=Lychee",
   },
   {
     id: 20,
     name: "Dragonfruit",
     price: 400,
     image: "https://via.placeholder.com/150?text=Dragonfruit",
   },
   {
     id: 21,
     name: "Apricot",
     price: 180,
     image: "https://via.placeholder.com/150?text=Apricot",
   },
   {
     id: 22,
     name: "Coconut",
     price: 50,
     image: "https://via.placeholder.com/150?text=Coconut",
   },
   {
     id: 23,
     name: "Raspberry",
     price: 280,
     image: "https://via.placeholder.com/150?text=Raspberry",
   },
   {
     id: 24,
     name: "Blackberry",
     price: 240,
     image: "https://via.placeholder.com/150?text=Blackberry",
   },
   {
     id: 25,
     name: "Tangerine",
     price: 90,
     image: "https://via.placeholder.com/150?text=Tangerine",
   },
   {
     id: 26,
     name: "Pear",
     price: 100,
     image: "https://via.placeholder.com/150?text=Pear",
   },
   {
     id: 27,
     name: "Pluot",
     price: 300,
     image: "https://via.placeholder.com/150?text=Pluot",
   },
   {
     id: 28,
     name: "Nectarine",
     price: 150,
     image: "https://via.placeholder.com/150?text=Nectarine",
   },
   {
     id: 29,
     name: "Clementine",
     price: 85,
     image: "https://via.placeholder.com/150?text=Clementine",
   },
   {
     id: 30,
     name: "Soursop",
     price: 200,
     image: "https://via.placeholder.com/150?text=Soursop",
   },
   {
     id: 31,
     name: "Longan",
     price: 280,
     image: "https://via.placeholder.com/150?text=Longan",
   },
   {
     id: 32,
     name: "Jackfruit",
     price: 250,
     image: "https://via.placeholder.com/150?text=Jackfruit",
   },
   {
     id: 33,
     name: "Mulberry",
     price: 220,
     image: "https://via.placeholder.com/150?text=Mulberry",
   },
   {
     id: 34,
     name: "Cranberry",
     price: 270,
     image: "https://via.placeholder.com/150?text=Cranberry",
   },
   {
     id: 35,
     name: "Elderberry",
     price: 300,
     image: "https://via.placeholder.com/150?text=Elderberry",
   },
   {
     id: 36,
     name: "Starfruit",
     price: 170,
     image: "https://via.placeholder.com/150?text=Starfruit",
   },
   {
     id: 37,
     name: "Tamarind",
     price: 50,
     image: "https://via.placeholder.com/150?text=Tamarind",
   },
   {
     id: 38,
     name: "Pomelo",
     price: 120,
     image: "https://via.placeholder.com/150?text=Pomelo",
   },
   {
     id: 39,
     name: "Figs",
     price: 200,
     image: "https://via.placeholder.com/150?text=Figs",
   },
   {
     id: 40,
     name: "Chilean Avocado",
     price: 250,
     image: "https://via.placeholder.com/150?text=Chilean+Avocado",
   },
   {
     id: 41,
     name: "Açaí",
     price: 350,
     image: "https://via.placeholder.com/150?text=Açaí",
   },
   {
     id: 42,
     name: "Galia Melon",
     price: 100,
     image: "https://via.placeholder.com/150?text=Galia+Melon",
   },
   {
     id: 43,
     name: "Kumquat",
     price: 180,
     image: "https://via.placeholder.com/150?text=Kumquat",
   },
   {
     id: 44,
     name: "Cranberry",
     price: 120,
     image: "https://via.placeholder.com/150?text=Cranberry",
   },
   {
     id: 45,
     name: "Durian",
     price: 400,
     image: "https://via.placeholder.com/150?text=Durian",
   },
   {
     id: 46,
     name: "Goji Berries",
     price: 500,
     image: "https://via.placeholder.com/150?text=Goji+Berries",
   },
   {
     id: 47,
     name: "Rambutan",
     price: 350,
     image: "https://via.placeholder.com/150?text=Rambutan",
   },
   {
     id: 48,
     name: "Bittermelon",
     price: 80,
     image: "https://via.placeholder.com/150?text=Bittermelon",
   },
   {
     id: 49,
     name: "Dragon Fruit",
     price: 350,
     image: "https://via.placeholder.com/150?text=Dragon+Fruit",
   },
   {
     id: 50,
     name: "Jujube",
     price: 450,
     image: "https://via.placeholder.com/150?text=Jujube",
   },
 ];
export default fruits